url: https://remote-rights.github.io
title: The Advocacy Toolkit

collections_dir: collections
collections:
  people-places:
    title: People & Places 
    output: true
    permalink: /:collection/:title
    in_nav: true
    position: 1

  strategy:
    title: What can I do?
    output: true
    permalink: /:collection/:title
    in_nav: true
    position: 2

  stories:
    title: Featured Stories
    output: true
    permalink: /:collection/:title
    in_nav: true
    position: 3
  
  schools:
    in_nav: false
    output: true