url: https://remote-rights.github.io
title: Remote Rights Advocacy Toolkit

collections_dir: collections
collections:
  change:
    title: Change
    output: true
    permalink: /:collection/:title
    custom: true

  stories:
    title: Featured Stories
    output: true
    permalink: /:collection/:title
    custom: true

  strategy:
    title: Advocacy Strategies
    output: true
    permalink: /:collection/:title
    custom: true

